#!/usr/bin/env bash
#
# Deploy AWS EC2 Instance - Wrapper script for Terraform deployment
#
# This script provides a convenient interface for deploying EC2 instances
# using the Terraform configuration in this directory.

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Source central configuration
if [[ -f "${PROJECT_ROOT}/common/config/vm-sizes.sh" ]]; then
    source "${PROJECT_ROOT}/common/config/vm-sizes.sh"
fi

print_usage() {
    cat << EOF
Usage: $(basename "$0") [OPTIONS] COMMAND

Deploy EC2 instances using Terraform and custom Debian AMI.

COMMANDS:
    init        Initialize Terraform
    plan        Show deployment plan
    apply       Deploy or update instance
    destroy     Destroy instance and all resources
    output      Show deployment outputs
    ssh         Connect to instance via SSH

OPTIONS:
    -a, --ami-id AMI_ID         AMI ID to use (required for init/apply)
    -k, --key-name KEY_NAME     SSH key pair name (required for init/apply)
    -n, --name INSTANCE_NAME    Instance name (default: debian13-dev-vm)
    -t, --type INSTANCE_TYPE    Instance type (default: t3.small)
    -r, --region AWS_REGION     AWS region (default: us-west-2)
    -h, --help                  Show this help message

EXAMPLES:
    # Initialize Terraform
    $(basename "$0") init

    # Plan deployment
    $(basename "$0") -a ami-0f7356d10733466d8 -k my-key plan

    # Deploy instance
    $(basename "$0") -a ami-0f7356d10733466d8 -k my-key apply

    # Connect via SSH
    $(basename "$0") ssh

    # Destroy instance
    $(basename "$0") destroy

NOTES:
    - Requires AWS CLI configured with appropriate credentials
    - Requires Terraform installed (>= 1.0)
    - SSH key pair must exist in AWS before deployment
    - Creates terraform.tfvars file with provided values

EOF
}

# Default values
AMI_ID=""
SSH_KEY_NAME=""
INSTANCE_NAME="debian13-dev-vm"
INSTANCE_TYPE="t3.small"
AWS_REGION="us-west-2"
AWS_PROFILE="kernelstate-dev"

# Parse command line arguments
COMMAND=""
while [[ $# -gt 0 ]]; do
    case $1 in
        -a|--ami-id)
            AMI_ID="$2"
            shift 2
            ;;
        -k|--key-name)
            SSH_KEY_NAME="$2"
            shift 2
            ;;
        -n|--name)
            INSTANCE_NAME="$2"
            shift 2
            ;;
        -t|--type)
            INSTANCE_TYPE="$2"
            shift 2
            ;;
        -r|--region)
            AWS_REGION="$2"
            shift 2
            ;;
        -h|--help)
            print_usage
            exit 0
            ;;
        init|plan|apply|destroy|output|ssh)
            COMMAND="$1"
            shift
            ;;
        *)
            echo -e "${RED}Error: Unknown option: $1${NC}"
            print_usage
            exit 1
            ;;
    esac
done

# Validate command
if [[ -z "$COMMAND" ]]; then
    echo -e "${RED}Error: No command specified${NC}"
    print_usage
    exit 1
fi

# Change to script directory
cd "${SCRIPT_DIR}"

# Function to check prerequisites
check_prerequisites() {
    # Check AWS CLI
    if ! command -v aws &> /dev/null; then
        echo -e "${RED}Error: AWS CLI not found. Please install it first.${NC}"
        exit 1
    fi

    # Check Terraform
    if ! command -v terraform &> /dev/null; then
        echo -e "${RED}Error: Terraform not found. Please install it first.${NC}"
        exit 1
    fi

    # Check AWS credentials
    if ! aws sts get-caller-identity --profile "${AWS_PROFILE}" &> /dev/null; then
        echo -e "${RED}Error: AWS credentials not configured or invalid.${NC}"
        echo "Run: aws configure --profile ${AWS_PROFILE}"
        exit 1
    fi
}

# Function to create terraform.tfvars
create_tfvars() {
    if [[ -z "$AMI_ID" ]] || [[ -z "$SSH_KEY_NAME" ]]; then
        echo -e "${RED}Error: AMI ID and SSH key name required for deployment${NC}"
        echo "Use: -a <ami-id> -k <key-name>"
        exit 1
    fi

    echo -e "${GREEN}Creating terraform.tfvars...${NC}"
    cat > terraform.tfvars << EOF
# Auto-generated by deploy.sh
ami_id        = "${AMI_ID}"
ssh_key_name  = "${SSH_KEY_NAME}"
instance_name = "${INSTANCE_NAME}"
instance_type = "${INSTANCE_TYPE}"
aws_region    = "${AWS_REGION}"
aws_profile   = "${AWS_PROFILE}"

# Network configuration (using default VPC)
use_default_vpc = true

# SSH access (WARNING: 0.0.0.0/0 allows from anywhere)
ssh_allowed_cidrs = ["0.0.0.0/0"]

# Environment tag
environment = "development"
EOF
    echo -e "${GREEN}Created terraform.tfvars${NC}"
}

# Function to get instance IP
get_instance_ip() {
    if [[ ! -f terraform.tfstate ]]; then
        echo -e "${RED}Error: No Terraform state found. Deploy an instance first.${NC}"
        exit 1
    fi
    
    terraform output -raw instance_public_ip 2>/dev/null || {
        echo -e "${RED}Error: Could not get instance IP. Is it deployed?${NC}"
        exit 1
    }
}

# Execute commands
case "$COMMAND" in
    init)
        echo -e "${GREEN}Initializing Terraform...${NC}"
        check_prerequisites
        terraform init
        echo -e "${GREEN}Terraform initialized successfully${NC}"
        ;;
    
    plan)
        echo -e "${GREEN}Planning deployment...${NC}"
        check_prerequisites
        create_tfvars
        terraform plan
        ;;
    
    apply)
        echo -e "${GREEN}Deploying EC2 instance...${NC}"
        check_prerequisites
        create_tfvars
        terraform apply
        
        if [[ $? -eq 0 ]]; then
            echo -e "\n${GREEN}Deployment successful!${NC}"
            echo -e "\nInstance details:"
            terraform output
            echo -e "\n${YELLOW}To connect:${NC}"
            echo "  $(terraform output -raw ssh_connection)"
        fi
        ;;
    
    destroy)
        echo -e "${YELLOW}This will destroy the instance and all associated resources.${NC}"
        read -p "Are you sure? (yes/no): " confirm
        if [[ "$confirm" == "yes" ]]; then
            check_prerequisites
            terraform destroy
            echo -e "${GREEN}Instance destroyed successfully${NC}"
        else
            echo -e "${YELLOW}Destruction cancelled${NC}"
        fi
        ;;
    
    output)
        check_prerequisites
        terraform output
        ;;
    
    ssh)
        check_prerequisites
        INSTANCE_IP=$(get_instance_ip)
        echo -e "${GREEN}Connecting to instance at ${INSTANCE_IP}...${NC}"
        ssh "admin@${INSTANCE_IP}"
        ;;
    
    *)
        echo -e "${RED}Error: Unknown command: $COMMAND${NC}"
        print_usage
        exit 1
        ;;
esac
