#cloud-config
# Example cloud-init user-data for local VM deployment
# This file shows various customization options

hostname: my-custom-vm
fqdn: my-custom-vm.localdomain

# User configuration
users:
  - name: debian
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1... your-key-here
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
  - name: developer
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1... developer-key-here
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo,docker
    shell: /bin/bash

# Set timezone
timezone: America/New_York

# Install additional packages on first boot
packages:
  - docker.io
  - docker-compose
  - nginx

# Run commands on first boot
runcmd:
  - systemctl enable docker
  - systemctl start docker
  - usermod -aG docker debian
  - echo "Custom setup complete" > /var/log/custom-setup.log

# Write files
write_files:
  - path: /etc/motd
    content: |
      Welcome to My Custom VM
      Managed by cloud-init
    permissions: '0644'
  - path: /home/debian/welcome.txt
    content: |
      This VM was customized via cloud-init!
    owner: debian:debian
    permissions: '0644'

# Disable automatic updates (optional)
package_update: false
package_upgrade: false
